// File generated by Gopher Sauce
// DO NOT EDIT!!
package types

type Choice struct {
	Text          string
	Interests     []string
	Weight, Index int
}
type Question struct {
	Text    string
	Choices []Choice
	Index   int
}
type Group struct {
	Text      string
	Questions []Question
	Resume    string
}
type Progress struct {
	Text  string
	Score float64
}
