// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package types

import "testing"

func TestChoice(t *testing.T) {

	t.Error("Test for data type Choice not implemented!!")
}

func TestQuestion(t *testing.T) {

	t.Error("Test for data type Question not implemented!!")
}

func TestGroup(t *testing.T) {

	t.Error("Test for data type Group not implemented!!")
}

func TestProgress(t *testing.T) {

	t.Error("Test for data type Progress not implemented!!")
}
