// File generated by Gopher Sauce
// DO NOT EDIT!!
package methods

import "log"

//
func ExtractTraits(args ...interface{}) map[string]int {

	defer func() {
		if n := recover(); n != nil {
			log.Println("Method ExtractTraits failed")
			log.Println("Reason : ", n)

		}
	}()

	var result = make(map[string]int)

	var groups = GetGroups()

	for _, g := range groups {

		for _, q := range g.Questions {

			for _, c := range q.Choices {

				for _, s := range c.Interests {

					_, ok := result[s]

					if !ok {
						result[s] = 0
					}
				}

			}

		}
	}

	return result

}
