// File generated by Gopher Sauce
// DO NOT EDIT!!
package methods

import (
	"log"

	"github.com/thestrukture/dap/api/globals"
	"github.com/thestrukture/dap/types"
)

//
func GetGroups(args ...interface{}) []types.Group {

	defer func() {
		if n := recover(); n != nil {
			log.Println("Method GetGroups failed")
			log.Println("Reason : ", n)

		}
	}()

	var groups []types.Group
	var count = 0

	for _, g := range globals.Groups {

		for iQ, q := range g.Questions {

			count++

			g.Questions[iQ].Index = count

			for iC, _ := range q.Choices {
				g.Questions[iQ].Choices[iC].Index = iC
			}
		}

		groups = append(groups, g)

	}

	return groups

}
