// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package methods

import "testing"

func TestGetGroups(t *testing.T) {

	t.Error("Test for method GetGroups not implemented!!")
}

func TestGetProgress(t *testing.T) {

	t.Error("Test for method GetProgress not implemented!!")
}

func TestExtractTraits(t *testing.T) {

	t.Error("Test for method ExtractTraits not implemented!!")
}
