// File generated by Gopher Sauce
// DO NOT EDIT!!
package handlers

import (
	"encoding/json"
	"net/http"

	gosweb "github.com/cheikhshift/gos/web"
	"github.com/gorilla/sessions"
	opentracing "github.com/opentracing/opentracing-go"

	sessionStore "github.com/thestrukture/dap/api/sessions"
)

var WebCache = gosweb.NewCache()

func mResponse(v interface{}) string {
	data, _ := json.Marshal(&v)
	return string(data)
}

func ApiAttempt(w http.ResponseWriter, r *http.Request, span opentracing.Span) (callmet bool) {
	var response string
	var session *sessions.Session

	var er error

	if session, er = sessionStore.Store.Get(r, "session-"); er != nil {
		session, _ = sessionStore.Store.New(r, "session-")
	}

	if r.Method == "RESET" {
		return true
	}
	if callmet {
		session.Save(r, w)
		session = nil
		if response != "" {
			//Unmarshal json
			//w.Header().Set("Access-Control-Allow-Origin", "*")
			w.Header().Set("Content-Type", "application/json")
			w.Write([]byte(response))
		}
		return
	}
	session = nil
	return
}
