// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/dap/types"
)

// Template path
var templateIDhQuestion = "tmpl/question.tmpl"

//
// Renders HTML of template
// hQuestion with struct types.Question
func HQuestion(d types.Question) string {
	return netbhQuestion(d)
}

// Render template with JSON string as
// data.
func nethQuestion(args ...interface{}) string {

	// Get data from JSON
	var d = netchQuestion(args...)
	return netbhQuestion(d)

}

// template render function
func netbhQuestion(d types.Question) string {
	localid := templateIDhQuestion
	name := "hQuestion"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netchQuestion(args ...interface{}) (d types.Question) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
