// This file was generated by Gopher Sauce.
// UPDATE IT TO BETTER TEST YOUR CODE.
package templates

import "testing"

func TesthGroup(t *testing.T) {

	t.Error("Test for template hGroup not implemented!!")
}

func TesthQuestion(t *testing.T) {

	t.Error("Test for template hQuestion not implemented!!")
}

func TesthProgress(t *testing.T) {

	t.Error("Test for template hProgress not implemented!!")
}
