// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/dap/types"
)

// Template path
var templateIDhProgress = "tmpl/progress.tmpl"

//
// Renders HTML of template
// hProgress with struct types.Progress
func HProgress(d types.Progress) string {
	return netbhProgress(d)
}

// Render template with JSON string as
// data.
func nethProgress(args ...interface{}) string {

	// Get data from JSON
	var d = netchProgress(args...)
	return netbhProgress(d)

}

// template render function
func netbhProgress(d types.Progress) string {
	localid := templateIDhProgress
	name := "hProgress"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netchProgress(args ...interface{}) (d types.Progress) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
