// File generated by Gopher Sauce
// DO NOT EDIT!!
package templates

import (
	"log"

	"github.com/thestrukture/dap/types"
)

// Template path
var templateIDhGroup = "tmpl/group.tmpl"

//
// Renders HTML of template
// hGroup with struct types.Group
func HGroup(d types.Group) string {
	return netbhGroup(d)
}

// Render template with JSON string as
// data.
func nethGroup(args ...interface{}) string {

	// Get data from JSON
	var d = netchGroup(args...)
	return netbhGroup(d)

}

// template render function
func netbhGroup(d types.Group) string {
	localid := templateIDhGroup
	name := "hGroup"
	defer templateRecovery(name, localid, &d)

	// render and return template result
	return executeTemplate(name, localid, &d)
}

// Unmarshal a json string to the template's struct
// type
func netchGroup(args ...interface{}) (d types.Group) {

	if len(args) > 0 {
		jsonData := args[0].(string)
		err := parseJSON(jsonData, &d)
		if err != nil {
			log.Println("error:", err)
			return
		}
	}

	return
}
